stages:
  - build
  - test


build:
  stage: build
  image: openjdk:17-alpine
  script:
      - chmod 744 ./gradlew
      - ./gradlew build
  artifacts:
    paths:
      - ./build/libs/

smoke test:
  stage: test
  image: openjdk:17-alpine
  before_script:
      - apk --no-cache add curl
  script:
      - java -jar ./build/libs/datamanagement-0.0.1-SNAPSHOT.jar &
      - sleep 30
      - curl http://localhost:5000/actuator/health | grep "UP"

static check:
    stage: test
    image: openjdk:17-alpine
    script:
        - ./gradlew pmdMain pmdTest
    artifacts:
        when: always
        paths:
            - ./build/reports/pmd